// integrations/nextjs/pages/index.jsx
import Head from 'next/head';
import content from '../frontaid.content';

export default function Index() {
  return (
      <>
        <Head>
          <title>{content.title}</title>
        </Head>
        <h1>{content.index.title}</h1>
        <div dangerouslySetInnerHTML={{__html: content.index.content}}></div>
      </>
  );
}

// integrations/nuxt-content/pages/index.vue
<template>
  <main>
    <h1 v-html="content.index.title"></h1>
    <div v-html="content.index.content"></div>
  </main>
</template>

<script>
import conf from '../conf';

export default {
  head() {
    return {title: this.content.title};
  },
  async asyncData({$content}) {
    const content = await $content(conf.CONTENT).fetch();
    return {content};
  },
};
</script>
